spring:
  application:
    name: healthcare-appointment-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/healthcare_appointments}
    username: ${DB_USERNAME:healthcare}
    password: ${DB_PASSWORD:healthcare}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    level: "%5p [correlationId:%X{correlationId:-none}]"
